apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: ecom
  labels:
    app: common
    managed-by: kubectl
data:
  # Kafka Configuration
  KAFKA_BROKERS: "kafka-service:9092"
  
  # Zipkin Configuration
  ZIPKIN_BASE_URL: "http://zipkin-service:9411"
  
  # Logging Configuration
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_ECOMMERCE: "DEBUG"
  
  # Spring Profiles
  SPRING_PROFILES_ACTIVE: "k8s"
